# Generated by Django 4.2.4 on 2023-09-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tutor_registration',
            new_name='tutor_registrationtable',
        ),
    ]
