# Generated by Django 4.2.4 on 2023-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_category_phoneno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_name',
            field=models.CharField(default='DefaultName', max_length=120),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
    ]
