# Generated by Django 4.2.4 on 2023-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_address_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='course_images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
