# Generated by Django 4.2.4 on 2023-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_course_name_coursedetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
