# Generated by Django 4.2.4 on 2023-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_course_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='tutor_profile_images')),
                ('instrument_teaching', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
