# Generated by Django 4.2.4 on 2023-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_tutor_registrationtable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_list',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
