# Generated by Django 4.2.4 on 2023-09-20 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_enrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='enrolled_learners',
            field=models.ManyToManyField(related_name='enrolled_courses', through='home.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
