# Generated by Django 4.2.4 on 2023-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_course_list_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.DeleteModel(
            name='video',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='instrument_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollments',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
    ]
