# Generated by Django 4.2.4 on 2023-10-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
