# Generated by Django 4.2.4 on 2023-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
