# Generated by Django 4.2.4 on 2024-01-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='course_detail',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='module',
        ),
    ]
