# Generated by Django 4.2.4 on 2024-02-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_question_is_active_response_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unlock_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.progress'),
        ),
    ]
