# Generated by Django 4.2.4 on 2024-02-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_question_is_active_response_quizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
