# Generated by Django 4.2.4 on 2024-02-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response_data',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
