# Generated by Django 4.2.4 on 2024-03-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='genre',
            field=models.CharField(blank=True, choices=[('Classical', 'Classical'), ('Jazz', 'Jazz'), ('Rock', 'Rock'), ('Pop', 'Pop')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=20),
        ),
    ]
