# Generated by Django 4.2.4 on 2024-04-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_assignments_allowed_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
