# Generated by Django 4.2.4 on 2024-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_coursedetail_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
