# Generated by Django 4.2.4 on 2024-04-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_coursedetail_sentiment_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name_plural': 'Course Details'},
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='sentiment_score',
        ),
    ]
